name: andrew_wommack
description: Andrew Wommack Teachings

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.2+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webfeed: ^0.7.0
  http: ^0.13.3
  flutter_riverpod: ^0.14.0+3
  equatable: ^2.0.2
  audio_service: ^0.17.1
  just_audio: ^0.7.5
  audio_session: ^0.1.3
  rxdart: ^0.27.1
  get_storage: ^2.0.2
  google_fonts: ^2.1.0
  shimmer: ^2.0.0
  marquee_text: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  share: ^2.0.4
  url_launcher: ^6.0.3
  flutter_downloader: ^1.6.1
  permission_handler: ^8.0.1
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.jpg"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
